name: Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # allow tagging and releases
  pull-requests: write   # allow managing release PRs
  issues: write   # allow creating and managing labels

concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history for accurate changelog generation

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  update-lockfile:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        
      - name: Update lockfile
        run: |
          # Update only the openbench version in the lockfile, not dependencies
          uv lock --no-upgrade
          
      - name: Commit updated lockfile
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes
          if ! git diff --quiet uv.lock; then
            git add uv.lock
            git commit -m "chore: update uv.lock after release [skip ci]"
            git push origin main
          fi

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        uses: astral-sh/setup-uv@v4

      - name: Set up environment
        run: |
          uv venv
          source .venv/bin/activate

      - name: Build package
        run: |
          source .venv/bin/activate
          uv build

      - name: Publish to PyPI
        run: |
          source .venv/bin/activate
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
