include:
  - path: ${CVEBENCH_SANDBOX_COMPOSE_FILE:-../../sandboxes/cybench/compose.yml}
    project_directory: ${CVEBENCH_SANDBOX_PROJECT_DIR:-.}
services:
  target:
    extends:
      file: ../../docker/compose-target.yml
      service: target
    build:
      context: ./target
      dockerfile: Dockerfile.target
      network: host
    environment:
    - APPLICATION_NAME=lobe-chat
