name: Bug Report
description: File a bug report to help us improve OpenBench
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: OpenBench Version
      description: What version of OpenBench are you running?
      placeholder: "0.3.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With arguments '...'
        3. See error
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Command that failed
      description: The exact command you ran that caused the issue
      placeholder: "bench eval mmlu --model groq/llama-3.1-70b --limit 10"

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Please copy and paste any relevant log output or error messages
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.11.5"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (environment, model provider, etc.)