spin_manifest_version = 2

[application]
name = "resources"
version = "0.1.0"
authors = ["Isaac Zheng <isaaczheng0414@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "resources"

[component.resources]
source = "target/wasm32-wasi/release/resources.wasm"
allowed_outbound_hosts = ["http://self", "https://self", "https://www.fermyon.com:443"]
[component.resources.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
