version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"

  # Enable version updates for Python dependencies via pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
    # Group all Python dependency updates together
    groups:
      python-dependencies:
        patterns:
          - "*"