name: Release Please

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

permissions:
  contents: write   # allow tagging and releases
  pull-requests: write   # allow managing release PRs
  issues: write   # allow creating and managing labels

concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history for accurate changelog generation

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
